### ISSUE TITLE
Does not support top level include with other keys

### ISSUE THREAD

**Issue by eugene-chernyshenko** [tanbro/pyyaml-include#22]
According to this answer 

> Till now, !include constructor can NOT be used at the TOP level, unless it's the only one node in whole YAML document.

The question is why?

https://github.com/tanbro/pyyaml-include/issues/7

**Comment by tanbro** [comment]
can this help?

<https://github.com/tanbro/pyyaml-include/issues/7#issuecomment-917827409>

**Comment by tanbro** [comment]
Duplicate of #7
