### ISSUE TITLE
Could you update the PyPI to new version to add PyYAML 6.0 support?

### ISSUE THREAD

**Issue by BillYuan** [tanbro/pyyaml-include#24]
Thanks for the good plugin to support include YAML file, it's very useful. 

But the latest version in https://pypi.org/project/pyyaml-include/, is still the old version, which meets the problem to support PyYAML6.0, could you update it to a new version? Thanks.

**Comment by tanbro** [comment]
The PyYAML 6.x support has been added at commit [8aa4fc7](https://github.com/tanbro/pyyaml-include/commit/8aa4fc7b3c68a26001fc57d250fd6be60db94a81), several mothes ago, but still not released.

I'll make a dist later.

**Comment by BillYuan** [comment]
Confirmed, it has been resolved in the new V1.3 version.
