### ISSUE TITLE
How to  concatenate two yaml files?

### ISSUE THREAD

**Issue by johnsonkee** [tanbro/pyyaml-include#25]
Hello, I want to concatenate two yaml files, what should I do?

for example, I have two different yaml files,
```yaml
# file1.yaml
name: 1
```

```yaml
# file2.yaml
class: 2
```

I want to concatenate these two files into one file after using pyyaml-include, as shown below
```
# merge_file.yaml
name: 1
class: 2
```

I would like to ask, what should I do to get this result?

Thank you very much.

**Comment by tanbro** [comment]
No, i think it won't work if we use including(s) directly.

Suppose we have such a YAML snippet:

```yaml
!include a.yml
!include b.yml
```

PyYAML will not parse the above into two tags, instead it's parsed as:

```yaml
!include "foo-1.yml !include foo-2.yml"
```

So we should put them in a sequnce or a mapping, eg:

```yaml
- !include a.yml
- !include b.yml
```

or 

```yaml
a: !include a.yml
b: !include b.yml
```
