### ISSUE TITLE
Python 3.10 unsopported?

### ISSUE THREAD

**Issue by afmurillo** [tanbro/pyyaml-include#36]
Hello,  I have been using pyyaml-include with Python3.8 and it worked well, but when I install the package on python3.10, the python source files are empty? 

I get this error: 
" from yamlinclude import YamlIncludeConstructor
ImportError: cannot import name 'YamlIncludeConstructor' from 'yamlinclude' (/usr/local/lib/python3.10/dist-packages/yamlinclude/__init__.py)"

The files "constructor.py", "readers.py", "version.py" inside "/usr/local/lib/python3.10/dist-packages/yamlinclude" are empty

**Comment by tanbro** [comment]
Is your problem happend on version [v1.3](https://github.com/tanbro/pyyaml-include/releases/tag/v1.3)?

According to Github action [2214613379](https://github.com/tanbro/pyyaml-include/actions/runs/2214613379), v1.3 is Ok for python3.10.

**Comment by afmurillo** [comment]
oh, sorry, nevermind, the problem has disappeared. It must have been an issue with my environment, thank you!
