### ISSUE TITLE
yaml writer?

### ISSUE THREAD

**Issue by lacraig2** [tanbro/pyyaml-include#37]
This is an interesting project that I'd like to integrate into my tools. I'd like to know if there's any support or interest for a writer class that respects includes.

As an example I'll refer to the first example in the README. Once the data has been read and potentially changed I may want to change the value of file2 name to be "3".

When I use yaml to dump the new dictionary to disk it will ignore the file structure and overwrite the values into one file. 

I'd like to know if there is a way to handle this such that the writer respects the existing structure. If not, is that something this project would be interested in?

**Comment by tanbro** [comment]
The library simply cannot write modified values back to YAML files yet.

Maybe we can do that by [PyYAML](https://pyyaml.org/) 's `Representer`
