### ISSUE TITLE
How to make the package work with setuptools lower than 61.0.0

### ISSUE THREAD

**Issue by Mingli-Yu** [tanbro/pyyaml-include#43]
I'm building the package from scratch. 

For some reason, I work on a system with an old setuptools which does not support PEP621 and is unable to extract name and version metadata in pyproject.toml  as https://github.com/pypa/setuptools/issues/3269#issuecomment-1254507377.

Is there any way to achieve the compatibility with the old setuptools? Thanks!

**Comment by tanbro** [comment]
Oh, pyyaml-include 2.0 has no plan for python earlier than 3.8.
as I known, python3.6 is installed with 59.6.0 by default, and python 3.7 is installed with 68.0.

Later, I'll review pyyaml-include 1.x , and try to make it work with python 3.6 + setuptools 59.x which does not support pyproject.toml

**Comment by tanbro** [comment]
@Mingli-Yu 
[v1.4.1](https://github.com/tanbro/pyyaml-include/releases/tag/v1.4.1) rollback to a pre PEP 518 build system. Python 3.6 support came back again, setuptools_scm and pyproject.toml was removed.

I think it may work on your environment.

**Comment by Mingli-Yu** [comment]
Thanks @tanbro , the new version 1.4.1 works well in my env with lower setuptool. Thank you very much!

**Comment by tanbro** [comment]
@Mingli-Yu all right ;)
