### ISSUE TITLE
Can we use alias with include?

### ISSUE THREAD

**Issue by paulhybryant** [tanbro/pyyaml-include#45]
For example:

something like:

vars: &vars !inc test.yaml

x:
  << *vars

**Comment by tanbro** [comment]
Similar discuss in #6, and @NoahFeinberg even implemeted that in #32.

But the feature have not been merged to v2.x til now, i think it's usable in v1.x

**Comment by paulhybryant** [comment]
Thank you. Do you mean it is merged now in v2.x?

**Comment by tanbro** [comment]
No, the feature is not available in v2.x until now. It may be implemented in the future.

**Comment by tanbro** [comment]
No, the feature is not available in v2.x until now. It may be implemented in the future.

**Comment by tanbro** [comment]
Closing this issue. This is the same fundamental limitation as #53 - PyYAML validates anchor/alias types before custom tags are processed. The merge key and alias features both require already-resolved mappings, but custom tag constructors run after validation.
