### ISSUE TITLE
is it currently supported to set an anchor for the included mapping?

### ISSUE THREAD

**Issue by WouterVH** [tanbro/pyyaml-include#6]
I was trying to have some inheritance, by including the shared yaml-file:

`
file1: !include include.d/1.yaml & shared

section1:
    <<: *shared
   foo: bar
`

**Comment by tanbro** [comment]
Oh, Sorry for late.

I tryed anchor, but it doesn't work.

Wo can put anchor **NEITHER** in main yaml file **NOR** in incuding files.

If so, the pyyaml will say: 

```
yaml.composer.ComposerError: found undefined alias 'anchor'
```

And it seems that there's no way to solve the problem... 😓
